---

- hosts: webservers
  gather_facts: no

  tasks:
    - name: Gather Services
      service_facts:

    - name: Output
      debug:
        msg:
          msg: 
            - "{{ ansible_facts['services']['sshd.service'] }}"



