---
# This playbook deploys all site configs

- name: apply base configuration to all sites
  hosts: all
  remote_user: ansibleuser
  become_user: root

  roles:
  - base

- name: Configure webservers
  hosts: webservers
  remote_user: ansibleuser
  become_user: root

  roles:
  - webservers
