---
# This example loops through a static list and checks for numbers greater than 5
- hosts: all
  vars:
    mydict: {"one": 1, "two": 2, "three": 3}

  tasks:
    - name: Loop through dictionary with conditional
      debug: 
        msg: "{{item.key}}: {{item.value}}"
      loop: "{{ query('dict', mydict) }}" 
      when: item.value > 2


