---
# This playbook contains base plays for all nodes

- name: Install base packages (listed in variable base_packages)
  yum: "name={{ item  }} state=present"
  loop: "{{ base_packages  }}"

- name: Start the firewalld service
  service: name=firewalld state=started enabled=yes

- name: Add users with dictionaries
  user:
    name: "{{ item.name }}"
    state: present
    groups: "{{ item.groups  }}"
  loop:
    - { name: 'webadmin1', groups: 'adm' }
    - { name: 'webadmin2', groups: 'wheel' }
